# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Autenticando usuáro no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviando para o DockerHub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            lfrodrigues17/kube-news:latest
            lfrodrigues17/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          images: lfrodrigues17/kube-news:${{github.run_number}}
          manifests: |
            ./kube-news/k8s/deployment.yaml
          
